# Point Cloud Demonstrations

## Registration

Registers two point clouds with slight offset.


In [1]:
import open3d as o3d
import numpy as np
import copy
import random
import copy

import utils

In [3]:
def draw_registration_result_original_color(source, target, transformation):
    source_temp = copy.deepcopy(source)
    source_temp.transform(transformation)
    o3d.visualization.draw_geometries([source_temp, target])

# load point clouds
base = o3d.io.read_point_cloud("./Point Clouds/Cleaner/1.ply")
source = o3d.io.read_point_cloud("./Point Clouds/Cleaner/8.ply")

# get 4x4 transformation matrix
trans = utils.register_clouds(base, source)

# show original clouds
o3d.visualization.draw_geometries([base, source])

# show aligned clouds
draw_registration_result_original_color(source, base, trans)


## Normals of point cloud
Shows the histogram of normals for the cloud. See utils module - running in notebook is much slower

## Outlier removal
Removes outliers and scatter artifacts from the pointcloud

In [4]:
cl, ind=utils.clean_cloud("./Point Clouds/Cleaner/1.ply", view=True)

## Cleaned and combined 8 clouds

In [6]:
base = o3d.io.read_point_cloud("./Point Clouds/combined_cloud_clean_cropped.ply")
o3d.visualization.draw_geometries([base])

# Region Growing Segmentation
Demonstrates region growing algorithm for downsampled cloud

In [ ]:
cl = o3d.io.read_point_cloud("./Point Clouds/combined_cloud_clean_cropped.ply")
pcd = cl.voxel_down_sample(0.01)

planes_list = utils.region_grow(pcd)

for plane in planes_list:
    colour = [random.uniform(0,1),random.uniform(0,1),random.uniform(0,1)]
    for i in plane:
        pcd.colors[i] = colour

o3d.visualization.draw_geometries([pcd])

# extract walls which is the largest object in the cloud

walls = planes_list[np.argmax(np.array([len(i) for i in planes_list]))]
walls = pcd.select_down_sample(walls)

0.23447606727037273%
0.2910737386804696%
0.37192755498060004%
0.3961836998706336%
0.4042690815006522%
0.460866752910738%
0.5498059508408759%
0.6306597671410064%
0.7357697283311815%
0.7842820181112597%
0.8166235446313119%
0.8166235446313119%
0.8166235446313119%
0.8166235446313119%
0.8166235446313119%
0.8166235446313119%
0.8651358344113791%
0.937904269081502%
0.9540750323415281%
0.9540750323415281%
0.9540750323415281%
1.0025873221216064%
1.0025873221216064%
1.0349288486416586%
1.0672703751617107%
1.0672703751617107%
1.0672703751617107%
1.115782664941789%
1.1885510996119009%
1.2936610608020649%
1.2936610608020649%
1.2936610608020649%
1.2936610608020649%
1.3017464424320835%
1.3179172056921096%
1.3179172056921096%
1.4230271668822736%
1.4230271668822736%
1.4311125485122922%
1.4311125485122922%
1.5523932729624823%
1.592820181112553%
1.6575032341526574%
1.7464424320827954%
1.7626131953428215%
1.7626131953428215%
1.770698576972829%
1.843467011642952%
1.8515523932729594%
1.8515523932729594%
1.90

9.8722509702458%
9.8722509702458%
9.8722509702458%
9.928848641655886%
9.95310478654593%
9.969275549805957%
9.969275549805957%
9.969275549805957%
10.017787839586024%
10.017787839586024%
10.017787839586024%
10.033958602846049%
10.033958602846049%
10.033958602846049%
10.106727037516173%
10.106727037516173%
10.187580853816304%
10.187580853816304%
10.28460543337646%
10.28460543337646%
10.28460543337646%
10.28460543337646%
10.413971539456668%
10.413971539456668%
10.413971539456668%
10.446313065976709%
10.502910737386806%
10.502910737386806%
10.502910737386806%
10.502910737386806%
10.502910737386806%
10.510996119016813%
10.510996119016813%
10.510996119016813%
10.510996119016813%
10.510996119016813%
10.510996119016813%
10.575679172056917%
10.591849935316944%
10.713130659767145%
10.761642949547223%
10.77781371280725%
10.866752910737388%
10.866752910737388%
10.866752910737388%
10.971862871927552%
10.971862871927552%
11.0608020698577%
11.0608020698577%
11.0608020698577%
11.0608020698577%
11.06080

19.687904269081503%
19.687904269081503%
19.687904269081503%
19.687904269081503%
19.687904269081503%
19.687904269081503%
19.687904269081503%
19.687904269081503%
19.687904269081503%
19.687904269081503%
19.687904269081503%
19.687904269081503%
19.687904269081503%
19.687904269081503%
19.712160413971535%
19.78492884864166%
19.78492884864166%
19.78492884864166%
19.78492884864166%
19.78492884864166%
19.78492884864166%
19.78492884864166%
19.78492884864166%
19.78492884864166%
19.78492884864166%
19.801099611901684%
19.801099611901684%
19.801099611901684%
19.817270375161712%
19.84961190168176%
19.84961190168176%
19.84961190168176%
19.84961190168176%
19.90620957309185%
19.922380336351875%
19.9385510996119%
19.9385510996119%
19.9385510996119%
19.9385510996119%
19.9385510996119%
19.9385510996119%
19.9385510996119%
19.9385510996119%
19.9385510996119%
19.9385510996119%
19.9385510996119%
19.9385510996119%
19.97897800776197%
19.97897800776197%
19.97897800776197%
19.97897800776197%
19.995148771022%
19.995

24.231888745148765%
24.231888745148765%
24.239974126778783%
24.34508408796895%
24.377425614489002%
24.38551099611902%
24.401681759379045%
24.401681759379045%
24.417852522639073%
24.42593790426908%
24.42593790426908%
24.434023285899098%
24.442108667529105%
24.46636481241915%
24.46636481241915%
24.46636481241915%
24.474450194049158%
24.474450194049158%
24.474450194049158%
24.474450194049158%
24.482535575679176%
24.50679172056921%
24.50679172056921%
24.51487710219923%
24.531047865459254%
24.531047865459254%
24.531047865459254%
24.571474773609314%
24.6280724450194%
24.644243208279427%
24.652328589909445%
24.652328589909445%
24.652328589909445%
24.652328589909445%
24.66849935316947%
24.66849935316947%
24.66849935316947%
24.66849935316947%
24.66849935316947%
24.66849935316947%
24.66849935316947%
24.700840879689522%
24.70892626131953%
24.70892626131953%
24.733182406209576%
24.733182406209576%
24.741267787839583%
24.7493531694696%
24.7493531694696%
24.7493531694696%
24.7493531694696%
24.749353

32.34961190168176%
32.37386804657179%
32.37386804657179%
32.4385510996119%
32.55174644243208%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.559831824062094%
32.60834411384217%
32.60834411384217%
32.60834411384217%
32.60834411384217%
32.60834411384217%
32.60834411384217%
32.60834411384217%
32.69728331177232%
32.69728331177232%
32.70536869340233%
32.70536869340233%
32.70536869340233%
32.82664941785253%
32.82664941785253%
32.84282018111255%
32.84282018111255%
32.85090556274256%
32.85090556274256%
32.87516170763261%
32.93175937904269%
32.93175937904269%
32.9964

37.75873221216042%
37.75873221216042%
37.75873221216042%
37.75873221216042%
37.75873221216042%
37.78298835705045%
37.78298835705045%
37.78298835705045%
37.79107373868047%
37.79107373868047%
37.79107373868047%
37.79107373868047%
37.79107373868047%
37.79107373868047%
37.79915912031048%
37.8719275549806%
37.88809831824062%
37.88809831824062%
37.90426908150065%
37.90426908150065%
37.91235446313066%
37.91235446313066%
37.91235446313066%
37.91235446313066%
37.91235446313066%
37.91235446313066%
37.91235446313066%
37.91235446313066%
37.91235446313066%
37.99320827943079%
38.057891332470895%
38.057891332470895%
38.057891332470895%
38.090232858990944%
38.098318240620955%
38.098318240620955%
38.130659767141005%
38.17108667529108%
38.17108667529108%
38.1872574385511%
38.1872574385511%
38.20342820181113%
38.20342820181113%
38.20342820181113%
38.23576972833118%
38.23576972833118%
38.24385510996119%
38.24385510996119%
38.24385510996119%
38.27619663648124%
38.27619663648124%
38.340879689521344%
38.3489

46.03816300129366%
46.03816300129366%
46.03816300129366%
46.03816300129366%
46.03816300129366%
46.03816300129366%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.16752910737387%
46.191785252263905%
46.191785252263905%
46.191785252263905%
46.191785252263905%
46.191785252263905%
46.23221216041398%
46.23221216041398%
46.23221216041398%
46.23221216041398%
46.23221216041398%
46.24029754204398%
46.24029754204398%
46.24029754204398%
46.24029754204398%
46.24029754204398%
46.24029754204398%
46.24029754204398%
46.24029754204398%
46.24029754204398%
46.24029754204398%
46.24029754204398%
46.24029754204398%
46.2402

51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.3098318240621%
51.42302716688227%
51.42302716688227%
51.42302716688227%
51.42302716688227%
51.42302716688227%
51.42302716688227%
51.42302716688227%
51.42302716688227%
51.42302716688227%
51.42302716688227%
51.42302716688227%
51.51196636481241%
51.51196636481241%
51.51196636481241%
51.536222509702455%
51.536222509

53.9375808538163%
53.9375808538163%
53.9375808538163%
53.9375808538163%
53.9375808538163%
53.9375808538163%
53.9375808538163%
53.9375808538163%
53.9375808538163%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.95375161707633%
53.99417852522639%
53.99417852522639%
54.01843467011642%
54.01843467011642%
54.01843467011642%
54.01843467011642%
54.01843467011642%
54.01843467011642%
54.01843467011642%
54.01843467011642%
54

59.9369340232859%
59.9369340232859%
59.9369340232859%
59.9369340232859%
59.9369340232859%
59.9369340232859%
59.9369340232859%
59.9369340232859%
59.9369340232859%
59.9369340232859%
59.9369340232859%
59.9369340232859%
59.9369340232859%
60.00970245795602%
60.04204398447607%
60.10672703751617%
60.10672703751617%
60.13098318240622%
60.13098318240622%
60.13098318240622%
60.13098318240622%
60.13098318240622%
60.13098318240622%
60.13098318240622%
60.13098318240622%
60.13098318240622%
60.13098318240622%
60.13098318240622%
60.13098318240622%
60.13098318240622%
60.13906856403622%
60.13906856403622%
60.13906856403622%
60.13906856403622%
60.13906856403622%
60.13906856403622%
60.13906856403622%
60.23609314359637%
60.30077619663648%
60.30077619663648%
60.30077619663648%
60.30077619663648%
60.30077619663648%
60.30077619663648%
60.30077619663648%
60.30077619663648%
60.30077619663648%
60.30077619663648%
60.308861578266495%
60.308861578266495%
60.308861578266495%
60.308861578266495%
60.308861578266495%
6

64.86093143596378%
64.86093143596378%
64.86093143596378%
64.86093143596378%
64.86093143596378%
64.86093143596378%
64.86093143596378%
64.86093143596378%
64.86093143596378%
64.86093143596378%
64.86093143596378%
64.86093143596378%
64.86093143596378%
64.86093143596378%
64.8771021992238%
64.8771021992238%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
64.93369987063389%
65.03072445019404%
65.03072445019404%
65.03072445019404%
65.03072445019404%
65.07923673997414%
65.07923673997414%
65.07923673997414%
65.07923673997414%
65.07923673997414%
65.07923673997414%
65.10349288486417%
65.11966364812419%
65.11966364812419%
65.11966364812419%
65.11966364812419%
65.11966364812419%
65.11966364812419%
65.11966364812419%
65.11966364812419%
65.11966364812419%
65.11966364812

67.496765847348%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.504851228978%
67.54527813712808%
67.54527813712808%
67.54527813712808%
67.54527813712808%
67.54527813712808%
67.54527813712808%
67.54527813712808%
67.54527813712808%
67.5614489003881%
67.5614489003881%
67.5614489003881%
67.5614489003881%
67.5614489003881%
67.5614489003881%
67.5614489003881%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%
67.60187580853815%


71.41817593790427%
71.41817593790427%
71.41817593790427%
71.41817593790427%
71.41817593790427%
71.41817593790427%
71.49902975420439%
71.49902975420439%
71.49902975420439%
71.49902975420439%
71.49902975420439%
71.49902975420439%
71.51520051746442%
71.5637128072445%
71.6283958602846%
71.6283958602846%
71.66073738680466%
71.66073738680466%
71.70116429495472%
71.70116429495472%
71.70116429495472%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.8143596377749%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.83053040103493%
71.8305304

73.6901681759379%
73.6901681759379%
73.69825355756791%
73.71442432082794%
73.71442432082794%
73.71442432082794%
73.71442432082794%
73.71442432082794%
73.746765847348%
73.746765847348%
73.746765847348%
73.746765847348%
73.746765847348%
73.746765847348%
73.77910737386804%
73.78719275549805%
73.78719275549805%
73.78719275549805%
73.78719275549805%
73.78719275549805%
73.78719275549805%
73.82761966364812%
73.82761966364812%
73.82761966364812%
73.8761319534282%
73.94081500646831%
73.97315653298836%
73.98124191461837%
73.98124191461837%
73.99741267787839%
74.02166882276843%
74.02166882276843%
74.02166882276843%
74.07018111254851%
74.07018111254851%
74.07018111254851%
74.07826649417852%
74.07826649417852%
74.07826649417852%
74.07826649417852%
74.07826649417852%
74.07826649417852%
74.11060802069858%
74.11060802069858%
74.11060802069858%
74.13486416558861%
74.14294954721863%
74.16720569210867%
74.16720569210867%
74.17529107373868%
74.17529107373868%
74.17529107373868%
74.17529107373868%
74.28848

79.9401681759379%
79.9401681759379%
79.9401681759379%
79.9401681759379%
79.9401681759379%
79.9401681759379%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
79.98059508408797%
80.01293661060802%
80.01293661060802%
80.01293661060802%
80.01293661060802%
80.01293661060802%
80.01293661060802%
80.02910737386804%
80.02910737386804%
80.02910737386804%
80.02910737386804%
80.02910737386804%
80.02910737386804%
80.02910737386804%
80.03719275549805%

86.26293661060802%
86.26293661060802%
86.26293661060802%
86.26293661060802%
86.27910737386804%
86.27910737386804%
86.27910737386804%
86.33570504527815%
86.33570504527815%
86.33570504527815%
86.33570504527815%
86.33570504527815%
86.33570504527815%
86.33570504527815%
86.33570504527815%
86.43272962483829%
86.43272962483829%
86.43272962483829%
86.44081500646831%
86.44081500646831%
86.44081500646831%
86.44890038809831%
86.44890038809831%
86.44890038809831%
86.44890038809831%
86.44890038809831%
86.44890038809831%
86.44890038809831%
86.44890038809831%
86.52166882276843%
86.52166882276843%
86.52975420439844%
86.53783958602847%
86.53783958602847%
86.53783958602847%
86.53783958602847%
86.54592496765846%
86.54592496765846%
86.58635187580855%
86.58635187580855%
86.58635187580855%
86.58635187580855%
86.59443725743856%
86.59443725743856%
86.59443725743856%
86.59443725743856%
86.59443725743856%
86.59443725743856%
86.59443725743856%
86.60252263906855%
86.60252263906855%
86.60252263906855%
86.634864165

91.14650711513583%
91.1869340232859%
91.1869340232859%
91.1869340232859%
91.1869340232859%
91.1869340232859%
91.1869340232859%
91.1869340232859%
91.1869340232859%
91.1869340232859%
91.1869340232859%
91.1869340232859%
91.24353169469599%
91.29204398447607%
91.29204398447607%
91.29204398447607%
91.29204398447607%
91.29204398447607%
91.29204398447607%
91.29204398447607%
91.29204398447607%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.42141009055628%
91.54269081500647%
91.55077619663649%
91.55077619663649%
91.55077619663649%
91.5

97.15394566623544%
97.15394566623544%
97.15394566623544%
97.21054333764553%
97.21054333764553%
97.21054333764553%
97.21054333764553%
97.21054333764553%
97.21054333764553%
97.21054333764553%
97.21054333764553%
97.21054333764553%
97.21054333764553%
97.21054333764553%
97.21054333764553%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.24288486416559%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29139715394567%
97.29948253557568%
97.29948253557568%
97.299482535

97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.76034928848641%
97.760349288

## Isolating each wall plane

In [15]:
planes_list = utils.region_grow(walls, 0.8, True)

colours = [[1,0,0],[0,1,0],[0,0,1]]

for plane, colour in zip(planes_list, colours):
    for i in plane:
        walls.colors[i] = colour

o3d.visualization.draw_geometries([walls])

# get normals for each plane
plane_normals = []
for plane in planes_list:
    # make a copy otherwise points a deleted from selection
    wall_cp = copy.deepcopy(walls)
    plane_points = np.asarray(wall_cp.select_down_sample(plane).points)
    
    pseudoinverse = np.linalg.pinv(plane_points.T)
    plane_normals.append(pseudoinverse.T.dot(np.ones(plane_points.shape[0])))
    
plane_normals = np.array(plane_normals)
print(plane_normals)


[[ 0.172442   -4.53981032 -1.09287925]
 [ 0.17390099 -4.5348036  -1.0929837 ]
 [ 0.95329086  0.27220854 -0.91976491]
 [-0.94490448  0.23151295 -1.01454493]
 [-0.94399753  0.22522192 -1.01627662]
 [ 0.95148873  0.26750579 -0.92162292]
 [ 1.16161677 -2.11498214 -1.25789771]
 [ 0.56403839 -1.36086399 -1.36739722]
 [-0.94191973  0.22937677 -1.01576782]
 [-0.9400275   0.23230626 -1.01579459]
 [ 0.17184159 -4.53803206 -1.09299422]
 [-0.11628297 -2.19718815 -1.23600322]
 [-0.93844092  0.23475586 -1.01595102]
 [-0.94803701  0.21890408 -1.01684526]
 [ 0.12645711 -1.71195794 -1.31794824]]


## SVD of Walls
Principle vectors pick out the normals of the wall

In [17]:
plane = planes_list[1]
wall_cp = copy.deepcopy(walls)
plane = wall_cp.select_down_sample(plane)
points = np.asarray(plane.points)
points -= np.mean(points, axis=0)
u, s, v = np.linalg.svd(points)

normal = np.matmul(np.linalg.pinv(points), np.ones(points.shape[0]))
normal /= np.linalg.norm(normal)

o3d.visualization.draw_geometries([plane, utils.create_vector_graph(v), utils.create_vector_graph([normal])])

## Match to plane in full size cloud

In [19]:
# now match to the original full size point cloud

cl.paint_uniform_color([0.5,0.5,0.5])
print(plane_normals)
for norm, colour in zip(plane_normals, colours):
    dot_match = np.abs(1-np.asarray(cl.points).dot(norm))
    for i in range(len(dot_match)):
        if dot_match[i] <0.04:
            cl.colors[i] = colour

# add normals for clearer viewing
if not cl.has_normals():
    cl.estimate_normals(o3d.geometry.KDTreeSearchParamHybrid(radius=0.04 * 2, max_nn=30))
o3d.visualization.draw_geometries([cl])

[[ 0.172442   -4.53981032 -1.09287925]
 [ 0.17390099 -4.5348036  -1.0929837 ]
 [ 0.95329086  0.27220854 -0.91976491]
 [-0.94490448  0.23151295 -1.01454493]
 [-0.94399753  0.22522192 -1.01627662]
 [ 0.95148873  0.26750579 -0.92162292]
 [ 1.16161677 -2.11498214 -1.25789771]
 [ 0.56403839 -1.36086399 -1.36739722]
 [-0.94191973  0.22937677 -1.01576782]
 [-0.9400275   0.23230626 -1.01579459]
 [ 0.17184159 -4.53803206 -1.09299422]
 [-0.11628297 -2.19718815 -1.23600322]
 [-0.93844092  0.23475586 -1.01595102]
 [-0.94803701  0.21890408 -1.01684526]
 [ 0.12645711 -1.71195794 -1.31794824]]


## Merging model clouds


In [4]:
scale = 1

cl1 = o3d.io.read_point_cloud("./Point Clouds/Field Clouds/Commander/1.3.ply")
cl1 = utils.isolate_model(cl1)
plane1 = utils.create_origin_plane(100)
cl1 += plane1
cl1.scale(scale)

for i in range(4):
    print(i)
    cl2 = o3d.io.read_point_cloud("./Point Clouds/Field Clouds/Commander/1.{}.ply".format(i+2))
    cl2 = utils.isolate_model(cl2)
    temp_cl = cl2 + plane1
    
    temp_cl.scale(scale)
    cl2.scale(scale)
    print("Registering")
    tran = utils.register_clouds(cl1, temp_cl, voxel_radius=[0.01, 0.005, 0.0001], max_iter=[1000,1000,10000])
    
    cl2 = cl2.transform(tran)
    cl1 += cl2
    cl1.estimate_normals(o3d.geometry.KDTreeSearchParamHybrid(radius=0.04 * 2, max_nn=30))
    
o3d.visualization.draw_geometries([cl1])

0
Registering
1
Registering
2
Registering
3
Registering


# Reference models

In [3]:
cmdr = o3d.io.read_point_cloud("./Point Clouds/Commander Ref.ply")
brdsd = o3d.io.read_point_cloud("./Point Clouds/Broadside Ref.ply")
o3d.visualization.draw_geometries([cmdr])
o3d.visualization.draw_geometries([brdsd])

# Recognising Models

In [20]:
cl = o3d.io.read_point_cloud("./Point Clouds/combined_cloud_clean_cropped.ply")
pcd = cl.voxel_down_sample(0.01)

planes_list = utils.region_grow(pcd)

# extract walls which is the largest object in the cloud

targets = [copy.deepcopy(pcd).select_down_sample(i) for i in planes_list if len(i)>3]
targets = [i.translate(-i.get_center()) for i in targets]



In [22]:
for i in targets:
    print(i.get_oriented_bounding_box().volume())
cmdr = o3d.io.read_point_cloud("./Point Clouds/Commander Ref.ply")
brdsd = o3d.io.read_point_cloud("./Point Clouds/Broadside Ref.ply")

cmdr_vol = cmdr.get_oriented_bounding_box().volume()
brdsd_vol = brdsd.get_oriented_bounding_box().volume()
print("Ref volumes:")
print("Commander: {}".format(cmdr.get_oriented_bounding_box().volume()))
print("Broadside: {}".format(brdsd.get_oriented_bounding_box().volume()))

print("Commander matching")
for pcd in targets:
    vol = pcd.get_oriented_bounding_box().volume()
    if vol > 0.3*cmdr_vol and vol < cmdr_vol:
        o3d.visualization.draw_geometries([pcd])
        
print("Broadside matching")
for pcd in targets:
    vol = pcd.get_oriented_bounding_box().volume()
    if vol > 0.3*brdsd_vol and vol < brdsd_vol:
        o3d.visualization.draw_geometries([pcd])

0.29369253516464067
1.931909394614609e-06
0.0002544654213212074
0.00013210731698131193
1.0404058191850966e-05
6.567504761104109e-07
4.8625064669989596e-08
Ref volumes:
Commander: 0.0003652094541903232
Broadside: 0.0005321971764080778
Commander matching
Broadside matching
